In [1]:
import pandas as pd
import numpy as np
from scipy.stats import multivariate_normal
from random import choices
from collections import Counter

In [2]:
def largest(num1, num2, num3):
    if (num1 > num2) and (num1 > num3):
        largest_num = 1
    elif (num2 > num1) and (num2 > num3):
        largest_num = 2
    else:
        largest_num = 3
    return largest_num


def BayesClassification(sample_n, act_miu1, act_miu2, act_sigma1, act_sigma2, act_prior1, act_prior2):
    random_seed=1000
    dist1=multivariate_normal(cov = act_sigma1, mean = act_miu1, seed = random_seed)
    dist2=multivariate_normal(cov = act_sigma2, mean = act_miu2, seed = random_seed)
    # Generate a series of 1s & 2s with above probability. It will be used to invoke the sampling function
    x=choices(population=[1,2], weights=[act_prior1,act_prior2], k=sample_n)
    y=Counter(x)
    half1=int(y[1]/2)
    half2=int(y[2]/2)
    print("First Distribution Estimate: ")
    print("Prior=> ",act_prior1)
    print("Mean=> ", act_miu1)
    print("Cov Matrix=>", act_sigma1)
    print("Second Distribution Estimate:")
    print( "Prior=> ",act_prior2 )
    print("Mean=> ", act_miu2)
    print("Cov Matrix=>", act_sigma2)
    # Sampling from the distribution of the FIRST class
    data1 = dist2.rvs(size = y[1])
    data1_train=data1[:half1]
    data1_test=data1[half1:]
    
    # Sampling from the distribution of the SECOND class
    data2 = dist1.rvs(size = y[2])
    data2_train=data2[:half2]
    data2_test=data2[half2:]
    
    print("Sample For First Distribution: ")
    print(data1[:10])
    print("Sample For Second Distribution: ")
    print(data2[:10])
    print("Training Data Geerated")
    
    # Get the total number of data for train
    total_train_records=len(data1_train)+len(data2_train)
    
    # Estimate the values of mean and cov matrices
    miu1_hat=np.mean(data1_train,0)
    sigma1_hat=np.cov(data1_train,rowvar=False)
    miu2_hat=np.mean(data2_train,0)
    sigma2_hat=np.cov(data2_train,rowvar=False)
    
    # Estimate the prior probability
    prior1_hat=len(data1_train)/total_train_records
    prior2_hat=len(data2_train)/total_train_records
    
    print("First Distribution Estimate:")
    print("Prior=> ",prior1_hat)
    print("Mean=> ", miu1_hat)
    print("Cov Matrix=>", sigma1_hat)

    print("Second Distribution Estimate:")
    print( "Prior=> ",prior2_hat )
    print("Mean=> ", miu2_hat)
    print("Cov Matrix=>", sigma2_hat)
    
    #Actual class data
    actual1=np.repeat(1,len(data1_test))
    actual2=np.repeat(2,len(data2_test))
    actual_classes=np.concatenate((actual1,actual2), axis=0)
    
    # Concatinate the data that is coming from both the classes for final classification
    final_test_data=np.concatenate((data1_test,data2_test), axis=0)
    
    # ESTIMATED the mis-classification rate
    # Calculate the components of the posteriori probability
    denom1=multivariate_normal.pdf(final_test_data, mean=miu1_hat, cov=sigma1_hat)*prior1_hat
    denom2=multivariate_normal.pdf(final_test_data, mean=miu2_hat, cov=sigma2_hat)*prior2_hat
    denominatior=denom1+denom2
    
    # Conpute the posteriori probability for both the classes
    class1_prob=denom1/denominatior
    class2_prob=denom2/denominatior
    
    class_prob_diff=class1_prob-class2_prob
    predicted_classes=[1 if x>0 else 2 for x in class_prob_diff]
    classification_diff=actual_classes-predicted_classes    
    estimated_mis_class_rate=len([1 for x in classification_diff if x!=0])/len(actual_classes)
    #estimated_mis_class_rate
    print("Misclassification Rate for ESTIMATED Parameters: ",estimated_mis_class_rate)
    
    # ACTUAL the mis-classification rate
    # Calculate the components of the posteriori probability
    denom1=multivariate_normal.pdf(final_test_data, mean=miu1, cov=sigma1)*act_prior1
    denom2=multivariate_normal.pdf(final_test_data, mean=miu2, cov=sigma2)*act_prior2
    denominatior=denom1+denom2
    
    # Conpute the posteriori probability for both the classes
    class1_prob=denom1/denominatior
    class2_prob=denom2/denominatior
    
    class_prob_diff=class1_prob-class2_prob
    predicted_classes=[1 if x>0 else 2 for x in class_prob_diff]
    classification_diff=actual_classes-predicted_classes    
    actual_mis_class_rate=len([1 for x in classification_diff if x!=0])/len(actual_classes)
    
    print("Misclassification Rate for ACTUAL Parameters: ",actual_mis_class_rate)
    
    return(actual_mis_class_rate-estimated_mis_class_rate)


def BayesClassificationTHREE(sample_n, act_miu1, act_miu2, act_miu3, act_sigma1, act_sigma2, act_sigma3, act_prior1, act_prior2, act_prior3):
    random_seed=1000
    dist1=multivariate_normal(cov = act_sigma1, mean = act_miu1, seed = random_seed)
    dist2=multivariate_normal(cov = act_sigma2, mean = act_miu2, seed = random_seed)
    dist3=multivariate_normal(cov = act_sigma3, mean = act_miu3, seed = random_seed)
    # Generate a series of 1s & 2s with above probability. It will be used to invoke the sampling function
    x=choices(population=[1,2,3], weights=[act_prior1,act_prior2,act_prior3], k=sample_n)
    y=Counter(x)
    half1=int(y[1]/2)
    half2=int(y[2]/2)
    half3=int(y[3]/2)
    print("First Distribution Estimate: ")
    print("Prior=> ",act_prior1)
    print("Mean=> ", act_miu1)
    print("Cov Matrix=>", act_sigma1)
    print("Second Distribution Estimate:")
    print( "Prior=> ",act_prior2 )
    print("Mean=> ", act_miu2)
    print("Cov Matrix=>", act_sigma2)
    print("Third Distribution Estimate:")
    print( "Prior=> ",act_prior3 )
    print("Mean=> ", act_miu3)
    print("Cov Matrix=>", act_sigma3)

    # Sampling from the distribution of the FIRST class
    data1 = dist1.rvs(size = y[1])
    data1_train=data1[:half1]
    data1_test=data1[half1:]
    
    # Sampling from the distribution of the SECOND class
    data2 = dist2.rvs(size = y[2])
    data2_train=data2[:half2]
    data2_test=data2[half2:]
    
    # Sampling from the distribution of the THIRD class
    data3 = dist3.rvs(size = y[3])
    data3_train=data3[:half3]
    data3_test=data3[half3:]

    
    print("Sample For First Distribution: ")
    print(data1[:10])
    print("Sample For Second Distribution: ")
    print(data2[:10])
    print("Sample For Third Distribution: ")
    print(data3[:10])

    print("Training Data Geerated")
    
    # Get the total number of data for train
    total_train_records=len(data1_train)+len(data2_train)+len(data3_train)
    
    # Estimate the values of mean and cov matrices
    miu1_hat=np.mean(data1_train,0)
    sigma1_hat=np.cov(data1_train,rowvar=False)
    miu2_hat=np.mean(data2_train,0)
    sigma2_hat=np.cov(data2_train,rowvar=False)
    miu3_hat=np.mean(data3_train,0)
    sigma3_hat=np.cov(data3_train,rowvar=False)

    
    # Estimate the prior probability
    prior1_hat=len(data1_train)/total_train_records
    prior2_hat=len(data2_train)/total_train_records
    prior3_hat=len(data3_train)/total_train_records
    
    print("First Distribution Estimate:")
    print("Prior=> ",prior1_hat)
    print("Mean=> ", miu1_hat)
    print("Cov Matrix=>", sigma1_hat)

    print("Second Distribution Estimate:")
    print( "Prior=> ",prior2_hat )
    print("Mean=> ", miu2_hat)
    print("Cov Matrix=>", sigma2_hat)
    
    print("Second Distribution Estimate:")
    print( "Prior=> ",prior3_hat)
    print("Mean=> ", miu3_hat)
    print("Cov Matrix=>", sigma3_hat)

    
    #Actual class data
    actual1=np.repeat(1,len(data1_test))
    actual2=np.repeat(2,len(data2_test))
    actual3=np.repeat(3,len(data3_test))
    actual_classes=np.concatenate((actual1,actual2,actual3), axis=0)
    
    # Concatinate the data that is coming from both the classes for final classification
    final_test_data=np.concatenate((data1_test,data2_test,data3_test), axis=0)
    
    # ESTIMATED the mis-classification rate
    # Calculate the components of the posteriori probability
    denom1=multivariate_normal.pdf(final_test_data, mean=miu1_hat, cov=sigma1_hat)*prior1_hat
    denom2=multivariate_normal.pdf(final_test_data, mean=miu2_hat, cov=sigma2_hat)*prior2_hat
    denom3=multivariate_normal.pdf(final_test_data, mean=miu3_hat, cov=sigma3_hat)*prior3_hat
    denominatior=denom1+denom2+denom3
    
    # Conpute the posteriori probability for both the classes
    class1_prob=denom1/denominatior
    class2_prob=denom2/denominatior
    class3_prob=denom3/denominatior
        
    #predicted_classes=largest(class1_prob,class2_prob,class3_prob)
    #print(predicted_classes)
    predicted_classes=np.repeat(0,len(class1_prob))
    for i in range(len(class1_prob)):
        predicted_classes[i]=largest(class1_prob[i],class2_prob[i],class3_prob[i])
    
    classification_diff=actual_classes-predicted_classes    
    estimated_mis_class_rate=len([1 for x in classification_diff if x!=0])/len(actual_classes)
    #estimated_mis_class_rate
    print("Misclassification Rate for ESTIMATED Parameters: ",estimated_mis_class_rate)
    
    # ACTUAL the mis-classification rate
    # Calculate the components of the posteriori probability
    denom1=multivariate_normal.pdf(final_test_data, mean=miu1, cov=sigma1)*act_prior1
    denom2=multivariate_normal.pdf(final_test_data, mean=miu2, cov=sigma2)*act_prior2
    denom3=multivariate_normal.pdf(final_test_data, mean=miu3, cov=sigma3)*act_prior3
    denominatior=denom1+denom2+denom3
    
    # Conpute the posteriori probability for both the classes
    class1_prob=denom1/denominatior
    class2_prob=denom2/denominatior
    class3_prob=denom3/denominatior
    
    predicted_classes=np.repeat(0,len(class1_prob))
    for i in range(len(class1_prob)):
        predicted_classes[i]=largest(class1_prob[i],class2_prob[i],class3_prob[i])

    
    #class_prob_diff=class1_prob-class2_prob
    #predicted_classes=[1 if x>0 else 2 for x in class_prob_diff]
    classification_diff=actual_classes-predicted_classes    
    actual_mis_class_rate=len([1 for x in classification_diff if x!=0])/len(actual_classes)
    
    print("Misclassification Rate for ACTUAL Parameters: ",actual_mis_class_rate)
    
    return(actual_mis_class_rate-estimated_mis_class_rate)


In [3]:
miu1=np.array([0,0])
sigma1=np.array([[1, 0], [0, 1]])

miu2=np.array([0,1])
sigma2=np.array([[1, -0.5], [-0.5, 2]])

miu3=np.array([-1,0.5])
sigma3=np.array([[0.75, 0.2], [0.2, 0.8]])

miu4=np.array([-2,1.3])
sigma4=np.array([[2, 0.8], [0.8, 1.6]])

In [4]:
#Case 1
misclass_rate_diff_n2000=BayesClassification(2000,miu1,miu2,sigma1,sigma2,0.75,0.25)
misclass_rate_diff_n5000=BayesClassification(5000,miu1,miu2,sigma1,sigma2,0.75,0.25)
misclass_rate_diff_n10000=BayesClassification(10000,miu1,miu2,sigma1,sigma2,0.75,0.25)
misclass_rate_diff_n20000=BayesClassification(20000,miu1,miu2,sigma1,sigma2,0.75,0.25)

print("Misclass Rate when N=2000: ",misclass_rate_diff_n2000)
print("Misclass Rate when N=5000: ",misclass_rate_diff_n5000)
print("Misclass Rate when N=10000: ",misclass_rate_diff_n10000)
print("Misclass Rate when N=20000: ",misclass_rate_diff_n20000)

First Distribution Estimate: 
Prior=>  0.75
Mean=>  [0 0]
Cov Matrix=> [[1 0]
 [0 1]]
Second Distribution Estimate:
Prior=>  0.25
Mean=>  [0 1]
Cov Matrix=> [[ 1.  -0.5]
 [-0.5  2. ]]
Sample For First Distribution: 
[[ 0.72137547  0.00520393]
 [ 0.54454998  1.18458255]
 [ 0.49141797  0.71985949]
 [-0.33378394  0.68897889]
 [-0.72055936  1.65837428]
 [-1.04253025  1.64118358]
 [ 0.3460294  -0.77999576]
 [ 0.18857962  0.78484253]
 [ 0.65924467  1.05048025]
 [-1.53481224  2.40935518]]
Sample For Second Distribution: 
[[-0.8044583   0.32093155]
 [-0.02548288  0.64432383]
 [-0.30079667  0.38947455]
 [-0.1074373  -0.47998308]
 [ 0.5950355  -0.46466753]
 [ 0.66728131 -0.80611561]
 [-1.19606983 -0.40596016]
 [-0.18237734  0.10319289]
 [-0.13842199  0.70569237]
 [ 1.27179528 -0.98674733]]
Training Data Geerated
First Distribution Estimate:
Prior=>  0.7477477477477478
Mean=>  [-0.01187862  0.99177593]
Cov Matrix=> [[ 0.99318339 -0.47934372]
 [-0.47934372  2.05780579]]
Second Distribution Estimat

In [5]:
#Case 2
misclass_rate_diff_n2000=BayesClassification(2000,miu1,miu2,sigma1,sigma2,0.5,0.5)
misclass_rate_diff_n5000=BayesClassification(5000,miu1,miu2,sigma1,sigma2,0.5,0.5)
misclass_rate_diff_n10000=BayesClassification(10000,miu1,miu2,sigma1,sigma2,0.5,0.5)
misclass_rate_diff_n20000=BayesClassification(20000,miu1,miu2,sigma1,sigma2,0.5,0.5)

print("Misclass Rate when N=2000: ",misclass_rate_diff_n2000)
print("Misclass Rate when N=5000: ",misclass_rate_diff_n5000)
print("Misclass Rate when N=10000: ",misclass_rate_diff_n10000)
print("Misclass Rate when N=20000: ",misclass_rate_diff_n20000)

First Distribution Estimate: 
Prior=>  0.5
Mean=>  [0 0]
Cov Matrix=> [[1 0]
 [0 1]]
Second Distribution Estimate:
Prior=>  0.5
Mean=>  [0 1]
Cov Matrix=> [[ 1.  -0.5]
 [-0.5  2. ]]
Sample For First Distribution: 
[[ 0.72137547  0.00520393]
 [ 0.54454998  1.18458255]
 [ 0.49141797  0.71985949]
 [-0.33378394  0.68897889]
 [-0.72055936  1.65837428]
 [-1.04253025  1.64118358]
 [ 0.3460294  -0.77999576]
 [ 0.18857962  0.78484253]
 [ 0.65924467  1.05048025]
 [-1.53481224  2.40935518]]
Sample For Second Distribution: 
[[-0.8044583   0.32093155]
 [-0.02548288  0.64432383]
 [-0.30079667  0.38947455]
 [-0.1074373  -0.47998308]
 [ 0.5950355  -0.46466753]
 [ 0.66728131 -0.80611561]
 [-1.19606983 -0.40596016]
 [-0.18237734  0.10319289]
 [-0.13842199  0.70569237]
 [ 1.27179528 -0.98674733]]
Training Data Geerated
First Distribution Estimate:
Prior=>  0.502
Mean=>  [0.00747941 0.97421647]
Cov Matrix=> [[ 0.97689311 -0.485003  ]
 [-0.485003    2.03104203]]
Second Distribution Estimate:
Prior=>  0.498

In [6]:
#Case 3
misclass_rate_diff_n2000=BayesClassification(2000,miu1,miu2,sigma1,sigma2,0.6,0.4)
misclass_rate_diff_n5000=BayesClassification(5000,miu1,miu2,sigma1,sigma2,0.6,0.4)
misclass_rate_diff_n10000=BayesClassification(10000,miu1,miu2,sigma1,sigma2,0.6,0.4)
misclass_rate_diff_n20000=BayesClassification(20000,miu1,miu2,sigma1,sigma2,0.6,0.4)

print("Misclass Rate when N=2000: ",misclass_rate_diff_n2000)
print("Misclass Rate when N=5000: ",misclass_rate_diff_n5000)
print("Misclass Rate when N=10000: ",misclass_rate_diff_n10000)
print("Misclass Rate when N=20000: ",misclass_rate_diff_n20000)

First Distribution Estimate: 
Prior=>  0.6
Mean=>  [0 0]
Cov Matrix=> [[1 0]
 [0 1]]
Second Distribution Estimate:
Prior=>  0.4
Mean=>  [0 1]
Cov Matrix=> [[ 1.  -0.5]
 [-0.5  2. ]]
Sample For First Distribution: 
[[ 0.72137547  0.00520393]
 [ 0.54454998  1.18458255]
 [ 0.49141797  0.71985949]
 [-0.33378394  0.68897889]
 [-0.72055936  1.65837428]
 [-1.04253025  1.64118358]
 [ 0.3460294  -0.77999576]
 [ 0.18857962  0.78484253]
 [ 0.65924467  1.05048025]
 [-1.53481224  2.40935518]]
Sample For Second Distribution: 
[[-0.8044583   0.32093155]
 [-0.02548288  0.64432383]
 [-0.30079667  0.38947455]
 [-0.1074373  -0.47998308]
 [ 0.5950355  -0.46466753]
 [ 0.66728131 -0.80611561]
 [-1.19606983 -0.40596016]
 [-0.18237734  0.10319289]
 [-0.13842199  0.70569237]
 [ 1.27179528 -0.98674733]]
Training Data Geerated
First Distribution Estimate:
Prior=>  0.5865865865865866
Mean=>  [-0.0159357   1.02102247]
Cov Matrix=> [[ 0.96220397 -0.47043395]
 [-0.47043395  2.05229202]]
Second Distribution Estimate:

In [7]:
#Case 4
misclass_rate_diff_n2000=BayesClassification(2000,miu1,miu3,sigma1,sigma3,0.7,0.3)
misclass_rate_diff_n5000=BayesClassification(5000,miu1,miu3,sigma1,sigma3,0.7,0.3)
misclass_rate_diff_n10000=BayesClassification(10000,miu1,miu3,sigma1,sigma3,0.7,0.3)
misclass_rate_diff_n20000=BayesClassification(20000,miu1,miu3,sigma1,sigma3,0.7,0.3)

print("Misclass Rate when N=2000: ",misclass_rate_diff_n2000)
print("Misclass Rate when N=5000: ",misclass_rate_diff_n5000)
print("Misclass Rate when N=10000: ",misclass_rate_diff_n10000)
print("Misclass Rate when N=20000: ",misclass_rate_diff_n20000)

First Distribution Estimate: 
Prior=>  0.7
Mean=>  [0 0]
Cov Matrix=> [[1 0]
 [0 1]]
Second Distribution Estimate:
Prior=>  0.3
Mean=>  [-1.   0.5]
Cov Matrix=> [[0.75 0.2 ]
 [0.2  0.8 ]]
Sample For First Distribution: 
[[-0.65607842  1.25681077]
 [-1.34911796  0.84178608]
 [-1.02438463  0.91802965]
 [-0.65724889  0.33904682]
 [-1.1253601  -0.17369658]
 [-0.97876813 -0.39833815]
 [ 0.01269282  1.18264481]
 [-0.93930817  0.68682799]
 [-1.31009492  0.956211  ]
 [-1.27157476 -0.93671021]]
Sample For Second Distribution: 
[[-0.8044583   0.32093155]
 [-0.02548288  0.64432383]
 [-0.30079667  0.38947455]
 [-0.1074373  -0.47998308]
 [ 0.5950355  -0.46466753]
 [ 0.66728131 -0.80611561]
 [-1.19606983 -0.40596016]
 [-0.18237734  0.10319289]
 [-0.13842199  0.70569237]
 [ 1.27179528 -0.98674733]]
Training Data Geerated
First Distribution Estimate:
Prior=>  0.702
Mean=>  [-0.99169431  0.49440528]
Cov Matrix=> [[0.76544537 0.20326764]
 [0.20326764 0.77376446]]
Second Distribution Estimate:
Prior=>  0

In [8]:
#Case 5
misclass_rate_diff_n2000=BayesClassification(2000,miu2,miu3,sigma2,sigma3,0.3,0.7)
misclass_rate_diff_n5000=BayesClassification(5000,miu2,miu3,sigma2,sigma3,0.3,0.7)
misclass_rate_diff_n10000=BayesClassification(10000,miu2,miu3,sigma2,sigma3,0.3,0.7)
misclass_rate_diff_n20000=BayesClassification(20000,miu2,miu3,sigma2,sigma3,0.3,0.7)

print("Misclass Rate when N=2000: ",misclass_rate_diff_n2000)
print("Misclass Rate when N=5000: ",misclass_rate_diff_n5000)
print("Misclass Rate when N=10000: ",misclass_rate_diff_n10000)
print("Misclass Rate when N=20000: ",misclass_rate_diff_n20000)

First Distribution Estimate: 
Prior=>  0.3
Mean=>  [0 1]
Cov Matrix=> [[ 1.  -0.5]
 [-0.5  2. ]]
Second Distribution Estimate:
Prior=>  0.7
Mean=>  [-1.   0.5]
Cov Matrix=> [[0.75 0.2 ]
 [0.2  0.8 ]]
Sample For First Distribution: 
[[-0.65607842  1.25681077]
 [-1.34911796  0.84178608]
 [-1.02438463  0.91802965]
 [-0.65724889  0.33904682]
 [-1.1253601  -0.17369658]
 [-0.97876813 -0.39833815]
 [ 0.01269282  1.18264481]
 [-0.93930817  0.68682799]
 [-1.31009492  0.956211  ]
 [-1.27157476 -0.93671021]]
Sample For Second Distribution: 
[[ 0.72137547  0.00520393]
 [ 0.54454998  1.18458255]
 [ 0.49141797  0.71985949]
 [-0.33378394  0.68897889]
 [-0.72055936  1.65837428]
 [-1.04253025  1.64118358]
 [ 0.3460294  -0.77999576]
 [ 0.18857962  0.78484253]
 [ 0.65924467  1.05048025]
 [-1.53481224  2.40935518]]
Training Data Geerated
First Distribution Estimate:
Prior=>  0.2982982982982983
Mean=>  [-0.9933372   0.51198914]
Cov Matrix=> [[0.81335649 0.21121144]
 [0.21121144 0.76722299]]
Second Distribu

In [9]:
#Case 6
misclass_rate_diff_n2000=BayesClassificationTHREE(2000,miu1,miu2,miu3,sigma1,sigma2,sigma3,0.3,0.4,0.3)
misclass_rate_diff_n5000=BayesClassificationTHREE(5000,miu1,miu2,miu3,sigma1,sigma2,sigma3,0.3,0.4,0.3)
misclass_rate_diff_n10000=BayesClassificationTHREE(10000,miu1,miu2,miu3,sigma1,sigma2,sigma3,0.3,0.4,0.3)
misclass_rate_diff_n20000=BayesClassificationTHREE(20000,miu1,miu2,miu3,sigma1,sigma2,sigma3,0.3,0.4,0.3)

print("Misclass Rate when N=2000: ",misclass_rate_diff_n2000)
print("Misclass Rate when N=5000: ",misclass_rate_diff_n5000)
print("Misclass Rate when N=10000: ",misclass_rate_diff_n10000)
print("Misclass Rate when N=20000: ",misclass_rate_diff_n20000)

First Distribution Estimate: 
Prior=>  0.3
Mean=>  [0 0]
Cov Matrix=> [[1 0]
 [0 1]]
Second Distribution Estimate:
Prior=>  0.4
Mean=>  [0 1]
Cov Matrix=> [[ 1.  -0.5]
 [-0.5  2. ]]
Third Distribution Estimate:
Prior=>  0.3
Mean=>  [-1.   0.5]
Cov Matrix=> [[0.75 0.2 ]
 [0.2  0.8 ]]
Sample For First Distribution: 
[[-0.8044583   0.32093155]
 [-0.02548288  0.64432383]
 [-0.30079667  0.38947455]
 [-0.1074373  -0.47998308]
 [ 0.5950355  -0.46466753]
 [ 0.66728131 -0.80611561]
 [-1.19606983 -0.40596016]
 [-0.18237734  0.10319289]
 [-0.13842199  0.70569237]
 [ 1.27179528 -0.98674733]]
Sample For Second Distribution: 
[[ 0.72137547  0.00520393]
 [ 0.54454998  1.18458255]
 [ 0.49141797  0.71985949]
 [-0.33378394  0.68897889]
 [-0.72055936  1.65837428]
 [-1.04253025  1.64118358]
 [ 0.3460294  -0.77999576]
 [ 0.18857962  0.78484253]
 [ 0.65924467  1.05048025]
 [-1.53481224  2.40935518]]
Sample For Third Distribution: 
[[-0.65607842  1.25681077]
 [-1.34911796  0.84178608]
 [-1.02438463  0.918029

In [10]:
#Case 7
misclass_rate_diff_n2000=BayesClassificationTHREE(2000,miu2,miu3,miu4,sigma2,sigma3,sigma4,0.2,0.7,0.1)
misclass_rate_diff_n5000=BayesClassificationTHREE(5000,miu2,miu3,miu4,sigma2,sigma3,sigma4,0.2,0.7,0.1)
misclass_rate_diff_n10000=BayesClassificationTHREE(10000,miu2,miu3,miu4,sigma2,sigma3,sigma4,0.2,0.7,0.1)
misclass_rate_diff_n20000=BayesClassificationTHREE(20000,miu2,miu3,miu4,sigma2,sigma3,sigma4,0.2,0.7,0.1)

print("Misclass Rate when N=2000: ",misclass_rate_diff_n2000)
print("Misclass Rate when N=5000: ",misclass_rate_diff_n5000)
print("Misclass Rate when N=10000: ",misclass_rate_diff_n10000)
print("Misclass Rate when N=20000: ",misclass_rate_diff_n20000)

First Distribution Estimate: 
Prior=>  0.2
Mean=>  [0 1]
Cov Matrix=> [[ 1.  -0.5]
 [-0.5  2. ]]
Second Distribution Estimate:
Prior=>  0.7
Mean=>  [-1.   0.5]
Cov Matrix=> [[0.75 0.2 ]
 [0.2  0.8 ]]
Third Distribution Estimate:
Prior=>  0.1
Mean=>  [-2.   1.3]
Cov Matrix=> [[2.  0.8]
 [0.8 1.6]]
Sample For First Distribution: 
[[ 0.72137547  0.00520393]
 [ 0.54454998  1.18458255]
 [ 0.49141797  0.71985949]
 [-0.33378394  0.68897889]
 [-0.72055936  1.65837428]
 [-1.04253025  1.64118358]
 [ 0.3460294  -0.77999576]
 [ 0.18857962  0.78484253]
 [ 0.65924467  1.05048025]
 [-1.53481224  2.40935518]]
Sample For Second Distribution: 
[[-0.65607842  1.25681077]
 [-1.34911796  0.84178608]
 [-1.02438463  0.91802965]
 [-0.65724889  0.33904682]
 [-1.1253601  -0.17369658]
 [-0.97876813 -0.39833815]
 [ 0.01269282  1.18264481]
 [-0.93930817  0.68682799]
 [-1.31009492  0.956211  ]
 [-1.27157476 -0.93671021]]
Sample For Third Distribution: 
[[-1.16780834  2.3518793 ]
 [-2.35907261  1.82697523]
 [-1.8526